### ISSUE TITLE
Unhandled network exception

### ISSUE THREAD

**Issue by liamaharon** [hubiinetwork/hubii-core#660]
Sometimes an unhandled network error will cause a system popup dialog. 

<img width="425" alt="screenshot 2018-12-18 at 12 08 52" src="https://user-images.githubusercontent.com/16665596/50151070-f919f280-0313-11e9-8b42-c65ebaff1b31.png">

Seems to be most reproducible when waking a system from sleep(?)

**Comment by liamaharon** [comment]
dev stacktrace:
```
Unhandled Promise Rejection
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (webpack-internal:///./node_modules/superagent/lib/client.js:621:13)
    at XMLHttpRequest.xhr.onreadystatechange (webpack-internal:///./node_modules/superagent/lib/client.js:703:19)
```

**Comment by liamaharon** [comment]
Appears to be an issue in the SDK. Will open a PR to ignore this particular exception until it's fixed upstream.
https://github.com/hubiinetwork/nahmii-sdk/issues/67

**Comment by liamaharon** [comment]
PR opened for a proper solution upstream, we can remove the band-aid fix once it's merged and we've updated our dependencies https://github.com/hubiinetwork/nahmii-sdk/pull/75
