### ISSUE TITLE
Investigate on the uncaught errors

### ISSUE THREAD

**Issue by katat** [hubiinetwork/hubii-core#777]
When the network environment is bad, sometimes it would prompt up the uncaught error dialog. This is probably related to the balance selectors

The error should be better handled so as to avoid prompting the error dialog.

**Comment by katat** [comment]
```
Unhandled Error
TypeError: Cannot read property 'balance' of undefined
    at DerivationPathContainer.render (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:186331:70)
    at vg (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370489:192)
    at ug (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370488:282)
    at yg (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370495:493)
    at fh (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370530:22)
    at gh (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370531:274)
    at Jh (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370546:348)
    at Kh (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370545:144)
    at Ph (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370557:371)
    at Id (file:///Applications/hubii-core.app/Contents/Resources/app.asar/build/main.js:370411:207)
```
I got this error on hubii core.
How to replicate?
- add a new wallet
- pick trezor
- add 1st address
- wallet added
- go to add a new wallet
- pick trezor again
- add 2nd address, then the error occurs and hubii core dies
