### ISSUE TITLE
Error on hubii-core 1.2.5.

### ISSUE THREAD

**Issue by adamgud** [hubiinetwork/hubii-core#785]
Unhandled Error
BigNumber Error: new BigNumber() not a number: 5.8e-
    at raise (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:18605:25)
    at file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:18593:33
    at new BigNumber (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:17619:67)
    at trimDecimals (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:167494:10)
    at file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:175697:21
    at Array.map (<anonymous>)
    at WalletItemCard.render (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:175694:49)
    at vg (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:370216:192)
    at ug (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:370215:282)
    at yg (file:///C:/Users/.../AppData/Local/Programs/hubii-core/resources/app.asar/build/main.js:370222:493)

**Comment by katat** [comment]
Hi @adamgud 

Thanks for reporting this issue. We have just pushed a patch release to fix it. Please have a try with https://github.com/hubiinetwork/hubii-core/releases/tag/v1.2.6, and see if it is resolved.

Best regards

**Comment by adamgud** [comment]
Yes. v1.2.6 works fine. Thanks!!
